### ISSUE TITLE
RuntimeError: expected scalar type Long but found Int

### ISSUE THREAD

**Issue by Eddy1998** [Furkan-Gulsen/chatbot-with-pytorch#1]
Hi Furkan
Im trying your code, but Im having problems while compiling the train.py script

I got the following error:

Traceback (most recent call last):
  File "C:/Folder/AppTestingOwn/chatbot-pytorch/train.py", line 86, in <module>
    loss = criterion(outputs, labels)
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\loss.py", line 1048, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\torch\nn\functional.py", line 2693, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\torch\nn\functional.py", line 2388, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: expected scalar type Long but found Int

Process finished with exit code 1

I didn't modify anything
Thaks for your help!

**Comment by Furkan-Gulsen** [comment]
Hello @Eddy1998 ,

The error says that the Pytorch library is not installed on your computer: For this, run the following command in the command system: 
`pip install torch`

Have a nice day...
